### ISSUE TITLE
这几天开始签到失败了

### ISSUE THREAD

**Issue by heiqingyu** [y-tai/zodgame_checkin#36]
Run python3 ./zodgame/zodgame.py "***"
could not detect version_main.therefore, we are assuming it is chrome 108 or higher
Traceback (most recent call last):
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 16[4](https://github.com/heiqingyu/zodgame_checkin/actions/runs/10445499777/job/28921522788#step:4:5), in <module>
    zodgame(cookie_string)
  File "D:\a\zodgame_checkin\zodgame_checkin\zodgame\zodgame.py", line 149, in zodgame
    WebDriverWait(driver, 240).until(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\selenium\webdriver\support\wait.py", line 10[5](https://github.com/heiqingyu/zodgame_checkin/actions/runs/10445499777/job/28921522788#step:4:6), in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by y-tai** [comment]
由于zodgame放宽了验证，这个问题已不会出现。
本人同时也在探寻其他绕过cloudflare的方法，感谢大家的支持。
